export const MIDTRANS_CLIENT_KEY = process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY;

export const BASE_API = process.env.NEXT_PUBLIC_BASE_API;

export const CLIENT_CRYPTO_SECRET = process.env.NEXT_PUBLIC_CLIENT_CRYPTO_SECRET;

export const MIDTRANS_SNAP_SCRIPT = process.env.NEXT_PUBLIC_MIDTRANS_SNAP_SCRIPT;

export const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;