import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flight and Hotel Reservations Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}, text-white font-sans`}>
        <div className="fixed top-0 w-full">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
